stages:
  - build

variables:

  DOCKERFILE_PATH: "/home/protas/Dockerfile"

build-docker:
  stage: build
  image: docker:stable
  only:
    - main
  services:
    - docker:dind
#  before_script:
#    - docker login -u Deployer -p ${ACCESS_TOKEN} registry.gitlab.com
  script:
    - docker build -t ${DOCKER_ENV_CI_REGISTRY_IMAGE} $DOCKERFILE_PATH .
    - docker push ${DOCKER_ENV_CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}