stages:
  - build

build-docker:
  stage: build
  image: docker:stable
  only:
    - main
  services:
    - docker:dind
#  before_script:
#    - docker login -u Deployer -p ${ACCESS_TOKEN} registry.gitlab.com
  script:
    - cd /home/protas/2048-game/
    - docker build -t 2048-game-image .
    - docker push ${DOCKER_ENV_CI_REGISTRY_IMAGE}