stages:
  - build

build-docker:
  stage: build
  image: docker:stable
  only:
    - main
  services:
    - docker:dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${ACCESS_TOKEN} registry.gitlab.com
  script:
    - VER="$(echo $CI_COMMIT_MESSAGE | sed 's/[^a-zA-Z0-9\.]//g')"
    - docker build -t 2048-game-image .
    - docker tag 2048-game-image $CI_REGISTRY_IMAGE:$VER
    - docker tag 2048-game-image $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE:$VER
    - docker push $CI_REGISTRY_IMAGE
  tags:
    - docker-build