---
driver:
  name: default
platforms:
  - name: instance
scenario:
  name: test-docker
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
